#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent
import secrets
import binascii

# Generate a random hex string of length 32
def generate_random_hex(length):
    random_bytes = secrets.token_bytes(length)
    random_hex = binascii.hexlify(random_bytes).decode('utf-8')
    return random_hex

# Set the SECRET environment variable
if not os.environ.get("SECRET"):
    secret = generate_random_hex(32)
    agent.set_env("SECRET", secret)
